feat: superwerker now in CDK
commit 6306d543cd043603db8d32b3077f9619ff5f6d7e
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Fri Nov 25 11:32:04 2022 +0100

    Convert JSON template to yaml when publishing

commit 20918c9aa88a94510c3f1859f1abc19e5502b170
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Tue Oct 4 08:35:30 2022 +0200

    Hardcode region list

    List has beeen created with scripts/ct+sso.sh

commit e2ddd0e879fba0c2bae396b28175886b9c9f762f
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Fri Sep 30 12:18:02 2022 +0200

    Release process

commit e695dcd1023004bc0203a42e5523406ac40e2f35
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Fri Sep 30 11:14:03 2022 +0200

    Give release user access to assets buckets

commit 4f0eb65a06dd58412e016db721f55bbbc53e8aa0
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Fri Sep 30 10:48:37 2022 +0200

    Prepare deployment for future release process

commit 8bddae72dc5b2fbf9203df633a36ca6b9a7d3b3b
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Thu Sep 15 14:42:02 2022 +0200

    Use CDK project in setup-test-env script

commit b7a183e7cebac2551f4364c0a56b394610555953
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Mon Sep 12 10:25:29 2022 +0200

    Disable asset bundling while testing

commit f5c2f8c7914e424424c61ec278165c5e062603cb
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Sat Sep 10 14:56:27 2022 +0200

    Allow to pass SUPERWERKER_VERSION as env var

commit f17c771f13829b5ebcdb7e034fdea6a415aec09b
Author: Robert von Massow <11364448+skomp@users.noreply.github.com>
Date:   Sun Sep 11 16:56:59 2022 +0200

    Migrate guardduty stack to cdk (#335)

commit 0f6127980fa94a4771f05092ed8edbdcb51413db
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Mon Sep 5 23:18:37 2022 +0200

    Remove failing GH action

commit 1fced5ff7a5c331e6c4e08d69aeb00577a88a4fe
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Mon Sep 5 21:41:56 2022 +0200

    Fix backup stack (lol,  ¯\_(ツ)_/¯)

commit 13a651d82575f59d4f5e45d3a92d66df528b0e29
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Mon Sep 5 14:27:10 2022 +0200

    Time out tests after 5 minutes

commit 357bbb460f914d2be1d44e8a7b3ec602758ee803
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Mon Sep 5 14:12:23 2022 +0200

    Maybe unbuffered?

commit 21d870955fdd68c386e3710e198729880bb62422
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Mon Sep 5 12:06:14 2022 +0200

    Don't capture output, hope this helps debugging

commit fcef257278ea96bde57c21002eca88cd38519104
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Mon Sep 5 10:09:45 2022 +0200

    Fix stack dependencies

commit 86411a9468a4798e8b11828de545ed5d4867a03e
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Mon Sep 5 08:25:05 2022 +0200

    Make sure all nested stacks have correct parameters

commit 355834213e027952f7414a1127bb5974be6c8d1d
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Sun Sep 4 23:18:16 2022 +0200

    Switch to custom resource provider framework

commit 4f57d9058e7203a13b48ce16498ac90c22266d83
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Sun Sep 4 21:47:27 2022 +0200

    Add debug logging

commit da11162e4b865a4f38f1b64df2d70a8576b1dfa5
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Sun Sep 4 21:25:09 2022 +0200

    Handle case where account is not in organization yet

    {
        "errorType": "AWSOrganizationsNotInUseException",
        "errorMessage": "Your account is not a member of an organization.",
        "code": "AWSOrganizationsNotInUseException",
        "message": "Your account is not a member of an organization.",
        "time": "2022-09-02T22:43:42.092Z",
        "requestId": "7e8604bc-ad76-4ee2-944b-fb9d25c98556",
        "statusCode": 400,
        "retryable": false,
        "retryDelay": 63.83174057769199,
        "stack": [
            "AWSOrganizationsNotInUseException: Your account is not a member of an organization.",
            "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
            "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
            "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
            "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)",
            "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
            "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
            "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
            "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
            "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)",
            "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
        ]
    }

commit 68e4bc28867c1770134e59e42998d43695c948dd
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Sat Sep 3 00:35:31 2022 +0200

    Fix IAM policy for custom resource

commit 79fde590a0d0d31987b32fc9c4ee62d71285a7fe
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Sat Sep 3 00:03:30 2022 +0200

    Arguments passed to lambda:Invoke must be string

commit ac67a33a4403d50ef28b7abbdae933ed1bade94c
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Fri Sep 2 23:23:21 2022 +0200

    Service name must be capitalized

    Received response status [FAILED] from custom resource. Message returned: Service lambda does not exist in AWS SDK version 2.1209.0. (RequestId: c34a19c2-f8b7-4ca5-820e-1ace932aeba8)

commit 73d0e34cacf12438a37c4cea2c1fcacd98ee59c0
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Fri Sep 2 23:16:20 2022 +0200

    Restructure to better see what's going on

commit e54a595650980b2aac79cdfd95b23fd199ccd301
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Fri Sep 2 22:36:14 2022 +0200

    add back parameters for cdk to work

commit ba1761d08ac9f03e65186cbdc0e4b3274238ade4
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Fri Sep 2 16:30:31 2022 +0200

    Update codebuild linux container

commit 8abb9f81d0f5b888bdc8168b93ea4d541301b03d
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Fri Sep 2 15:58:56 2022 +0200

    buildspec cdk hac

commit 99fa6c0f3c47725f70d464ac7e080a769243d669
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Fri Sep 2 15:58:46 2022 +0200

    Clean up

commit 9a3ddf455e3c7a87c3cb5821bcb6e10b889a3dc7
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Fri Sep 2 15:55:21 2022 +0200

    fix tsconfig

commit 9a6c212bbffbc63b3920df5b4113b1815c3f4d25
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Fri Sep 2 15:25:06 2022 +0200

    Remove dead files

commit e48f7439ff414f91fbca79590a4e90b0ca49bf66
Author: sbstjn <mail@sbstjn.com>
Date:   Fri Sep 2 13:12:45 2022 +0200

    show identity

commit 0dc3b73e9bc0e94a31eba12f79ed7ed922dea10a
Author: sbstjn <mail@sbstjn.com>
Date:   Fri Sep 2 13:07:08 2022 +0200

    set session permission

commit 0a86f0aa8b0936f7ab14091d89930fed87ee5c21
Author: sbstjn <mail@sbstjn.com>
Date:   Fri Sep 2 13:05:20 2022 +0200

    set session name

commit 256eac7a19832130037abdfe3e77cc2ad6fba700
Author: sbstjn <mail@sbstjn.com>
Date:   Fri Sep 2 13:01:54 2022 +0200

    add github action for synth&publish

commit 0ed395999145e944ee0a5087ad80edc4faefde79
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Fri Sep 2 12:24:03 2022 +0200

    Shell out instead of lib usage

commit c23b7b1a77ba020bd4e610eb666f9d289342b41a
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Fri Sep 2 12:08:59 2022 +0200

    publish assets script

commit 9809712f43c6baacbfa0d43c8b7b0b873f678029
Author: sbstjn <mail@sbstjn.com>
Date:   Fri Sep 2 10:36:42 2022 +0200

    wip

commit d7deeb19e3f49d0fa177090a515ca55a43c8424e
Author: sbstjn <mail@sbstjn.com>
Date:   Thu Sep 1 15:28:19 2022 +0200

    move files

commit 4790049383cf9371a7465f383d6f91770e442088
Author: sbstjn <mail@sbstjn.com>
Date:   Thu Sep 1 15:03:04 2022 +0200

    refactor email address generation for cdk upgrade path

commit 384d19f5e68e43c5ee2688d6aaec7b8f0e564a1c
Author: sbstjn <mail@sbstjn.com>
Date:   Thu Sep 1 11:54:38 2022 +0200

    wip

commit 9326bdf300088b7cfc5a03e8215eb1f137d35047
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Thu Sep 1 10:24:02 2022 +0200

    Budget stack, and ignore quickstart stuff

commit d14803dab366cbf241ca0df3e2d398c5c93bee4c
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Thu Sep 1 09:38:28 2022 +0200

    Latest version of cdk

commit cf917664be7b0e5ebbd7cc9b2a44024b184eaa24
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Thu Sep 1 09:00:30 2022 +0200

    Port parameters of SuperwerkerStack

commit 36f92ac00ca8b6c55ebc70136c0f868eefa7b8fa
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Wed Aug 31 23:47:16 2022 +0200

    Fix indentation of description

commit 23a25a5c27cc8dde80adc79cb4ed59ab8b9fa493
Author: Jan Brauer <jan.brauer@superluminar.io>
Date:   Wed Aug 31 23:46:21 2022 +0200

    First CDK draft

    The config files have been created via projen and it's eject feature.