feat: Rewrite superwerker using CDK (#332)
* First CDK draft

The config files have been created via projen and it's eject feature.

* Fix indentation of description

* Port parameters of SuperwerkerStack

* Latest version of cdk

* Budget stack, and ignore quickstart stuff

* wip

* refactor email address generation for cdk upgrade path

* move files

* wip

* publish assets script

* Shell out instead of lib usage

* add github action for synth&publish

* set session name

* set session permission

* show identity

* Remove dead files

* fix tsconfig

* Clean up

* buildspec cdk hac

* Update codebuild linux container

* add back parameters for cdk to work

* Restructure to better see what's going on

* Service name must be capitalized

Received response status [FAILED] from custom resource. Message returned: Service lambda does not exist in AWS SDK version 2.1209.0. (RequestId: c34a19c2-f8b7-4ca5-820e-1ace932aeba8)

* Arguments passed to lambda:Invoke must be string

* Fix IAM policy for custom resource

* Handle case where account is not in organization yet

{
    "errorType": "AWSOrganizationsNotInUseException",
    "errorMessage": "Your account is not a member of an organization.",
    "code": "AWSOrganizationsNotInUseException",
    "message": "Your account is not a member of an organization.",
    "time": "2022-09-02T22:43:42.092Z",
    "requestId": "7e8604bc-ad76-4ee2-944b-fb9d25c98556",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 63.83174057769199,
    "stack": [
        "AWSOrganizationsNotInUseException: Your account is not a member of an organization.",
        "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)",
        "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
    ]
}

* Add debug logging

* Switch to custom resource provider framework

* Make sure all nested stacks have correct parameters

* Fix stack dependencies

* Don't capture output, hope this helps debugging

* Maybe unbuffered?

* Time out tests after 5 minutes

* Fix backup stack (lol,  ¯\_(ツ)_/¯)

* Remove failing GH action

* Migrate guardduty stack to cdk (#335)

* Allow to pass SUPERWERKER_VERSION as env var

* Disable asset bundling while testing

* Use CDK project in setup-test-env script

* Prepare deployment for future release process

* Give release user access to assets buckets

* Release process

* Hardcode region list

List has beeen created with scripts/ct+sso.sh

* Convert JSON template to yaml when publishing

* Fix IAM permissions for publish assets

* chore: bump dependencies to latest

Signed-off-by: Manuel Vogel <mavogel@posteo.de>

* chore: bump codebuild image to v4.0

Signed-off-by: Manuel Vogel <mavogel@posteo.de>

* feat: added test for guardduty

Signed-off-by: Manuel Vogel <mavogel@posteo.de>

* update Github actions

* add default region

* rename steps in build job

* chore: remove old template

* feat: commit linting

* fix: Add working dir for PR validation action

* fix: clone git repo in sufficient depth

* fix: Disable body line length checking

* docs/update dev cycle (#354)

* docs: enhance development guide
* docs: fix aws confg source profile
* docs: update release process
* docs: add sso login for YourSandboxAdmin
* docs: add link to the conventional commit format

* feat: Lint PR title

* fix: PR linting

Signed-off-by: Manuel Vogel <mavogel@posteo.de>
Co-authored-by: sbstjn <mail@sbstjn.com>
Co-authored-by: Robert von Massow <11364448+skomp@users.noreply.github.com>
Co-authored-by: Manuel Vogel <mavogel@posteo.de>
Co-authored-by: VerenaTraub <verenatraubmail@gmail.com>